<script>

//This string contains the VSCode Settings. Generated by the create_settings_file python file.

export const settings =

'{\n' + 
'\n' + 
'    /**\n' + 
'        How to Open this settings json file\n' + 
'\n' + 
'        1. Open Visual Studio code\n' + 
'\n' + 
'        2. Press command + shift + p\n' + 
'\n' + 
'        3. Lookup and click on the "Preferences: Open Settings (JSON)" option\n' + 
'           in the drop down menu.\n' + 
'    */\n' + 
'    "security.workspace.trust.untrustedFiles": "open",\n' + 
'    //"python.defaultInterpreterPath": "/usr/bin/python3",\n' + 
'\n' + 
'    //My Default python path for vs code\n' + 
'    "python.defaultInterpreterPath": "~/.pyenv/versions/3.10.6/bin/python",\n' + 
'\n' + 
'    //Sets Tab Size to 4 spaces\n' + 
'    "editor.tabSize": 4,\n' + 
'\n' + 
'    // Set Tab indentation size to 2 for Vue, JavaScript, JSX, and Typescript\n' + 
'    "[vue]": {\n' + 
'        "editor.tabSize": 2,\n' + 
'    },\n' + 
'    "[javascript]": {\n' + 
'        "editor.tabSize": 2,\n' + 
'    },\n' + 
'    "[javascriptreact]": {\n' + 
'        "editor.tabSize": 2,\n' + 
'    },\n' + 
'    "[typescriptreact]": {\n' + 
'        "editor.tabSize": 2,\n' + 
'    },\n' + 
'\n' + 
'    //Disables Run | Debug text\n' + 
'    "editor.codeLens": false,\n' + 
'\n' + 
'    //Turns off weird coloring of Java brackets\n' + 
'    "editor.bracketPairColorization.enabled": false,\n' + 
'\n' + 
'    //Sets the maximum number of items in a json file to 50,000 without\n' + 
'    //warning about performance issues. Was originally 5,000.\n' + 
'    "json.maxItemsComputed": 50000,\n' + 
'\n' + 
'    //Disables yellow underline for reportMissingModuleSource\n' + 
'    //reportMissingImports and errors in Python.\n' + 
'    // "python.analysis.diagnosticSeverityOverrides" : {\n' + 
'    //     "reportMissingModuleSource" : "none",\n' + 
'    //     "reportMissingImports": "none"\n' + 
'    // },\n' + 
'\n' + 
'    //Opens Live Server in Chrome by Default\n' + 
'    "liveServer.settings.CustomBrowser": "chrome",\n' + 
'\n' + 
'    //Turns off the warning about unusual characters in a txt file.\n' + 
'    "editor.unusualLineTerminators" : "off",\n' + 
'\n' + 
'    /** Gets rid of autofill parameter suggestions in method calls in java */\n' + 
'    "editor.inlayHints.enabled": "off",\n' + 
'\n' + 
'    //Changes font size to 13.5\n' + 
'    "editor.fontSize": 13.5,\n' + 
'\n' + 
'    "launch": {\n' + 
'        "configurations": [],\n' + 
'        "compounds": []\n' + 
'    },\n' + 
'\n' + 
'    // Set to false to show .git folder\n' + 
'    "files.exclude": {\n' + 
'        "**/.git": false,\n' + 
'    },\n' + 
'\n' + 
'    /**\n' + 
'        How to change a color\n' + 
'     1. hover over the keyword whose color you want changed\n' + 
'     2. Press command + shift + p on mac\n' + 
'     3. Search and click "Developer: Inspect Editor Tokens and Scopes"\n' + 
'     4. In the box that opens next to "textmate scopes" copy the first line\n' + 
'        and paste it under the scope keyword that\'s above the color you want\n' + 
'        to change the keyword too. If it doesn\'t work try the other lines.\n' + 
'     5. To stop inspecting the tokens press command + shift + p\n' + 
'        then press enter\n' + 
'    */\n' + 
'  "editor.tokenColorCustomizations": {\n' + 
'\n' + 
'    "[Atom One Dark]": {\n' + 
'        "textMateRules": [\n' + 
'\n' + 
'            //Changes function calls to blue ,\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes function calls to blue */\n' + 
'                    "meta.function-call.generic.python",\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#61AFEF" //Blue\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'            //Changes colors to gray.\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes function parameters to gray */\n' + 
'                    "variable.parameter.function.language.python",\n' + 
'                    "meta.function.parameters.python",\n' + 
'                    "meta.function.python",\n' + 
'                    "source.python",\n' + 
'\n' + 
'                    /** Changes __name__ to gray. */\n' + 
'                    "support.variable.magic.python",\n' + 
'\n' + 
'                    /** Changes variables to gray in java */\n' + 
'                    "variable.other.definition.java",\n' + 
'\n' + 
'                    /** Changes out keyword to gray */\n' + 
'                    "variable.other.object.property.java",\n' + 
'\n' + 
'                    /** The console in console.close() gets turned to gray in java */\n' + 
'                    "variable.other.object.java",\n' + 
'\n' + 
'                    // "meta.try.body.java"\n' + 
'\n' + 
'                    /** Changes brackets in array declaration to gray. String[] */\n' + 
'                    "punctuation.bracket.square.java",\n' + 
'\n' + 
'                    /** Makes imports in java gray */\n' + 
'                    "storage.modifier.import.java",\n' + 
'\n' + 
'                    /** Changes certain functions from library pink in python */\n' + 
'                    "meta.indexed-name.python",\n' + 
'\n' + 
'                    /** Changes the file keyword to gray" */\n' + 
'                    "variable.legacy.builtin.python",\n' + 
'\n' + 
'                    /** Make C# static class variables gray */\n' + 
'                    "entity.name.variable.field.cs",\n' + 
'\n' + 
'                    /** Makes const variables in Javascript gray */\n' + 
'                    "variable.other.constant.js",\n' + 
'\n' + 
'                    /** In Vue.js make . in car.Brand object gray */\n' + 
'                    "punctuation.accessor.js"\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#ABB2BF" //Gray\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'            //Changes f in f string to green\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes f in f string to green */\n' + 
'                    "storage.type.string.python",\n' + 
'\n' + 
'                    /** Changes escape characters to green */\n' + 
'                    "constant.character.escape.java",\n' + 
'\n' + 
'                    "string.quoted.single.python",\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#98C379" //Green\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'            //Changes colors to red\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes object attributes to red */\n' + 
'                    "meta.attribute.python",\n' + 
'                    /** Changes brackets to red */\n' + 
'                    "constant.character.format.placeholder.other.python",\n' + 
'                    //Changes attribute to red in C#. Example song.Instrument. Instrument is red\n' + 
'                    "variable.other.object.property.cs",\n' + 
'                    //Changes The "<" character in List<string> to red.\n' + 
'                    "punctuation.definition.typeparameters.begin.cs",\n' + 
'                    //Changes The ">" character in List<string> to red.\n' + 
'                    "punctuation.definition.typeparameters.end.cs"\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#E06C75"\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'            //Changes certain functions from library such as testbed.devices[devices] to pink.\n' + 
'            // {\n' + 
'            //     "scope": [\n' + 
'            //         /** Changes certain functions from library pink in python */\n' + 
'            //         "meta.indexed-name.python",\n' + 
'            //     ],\n' + 
'            //     "settings": {\n' + 
'            //         "foreground": "#F3D0F7"\n' + 
'            //     }\n' + 
'            // },\n' + 
'\n' + 
'            //Changes certain keywords to yellow in Java.\n' + 
'            {\n' + 
'                "scope": [\n' + 
'\n' + 
'                    /** Changes System keyword to yellow */\n' + 
'                    "variable.other.object.java",\n' + 
'\n' + 
'                    /** Changes parameter type to yellow and return type. */\n' + 
'                    "storage.type.primitive.java",\n' + 
'\n' + 
'                    //"entity.name.function.java"\n' + 
'\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#E5C07B"\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'            //Changes colors to dark gray.\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Makes keywords in comments in java dark gray" */\n' + 
'                    "keyword.other.documentation.javadoc.java",\n' + 
'\n' + 
'                    /** Changes parameter to dark gray in java*/\n' + 
'                    "variable.parameter.java",\n' + 
'\n' + 
'                    /** Makes descriptions in comments dark gray */\n' + 
'                    "comment.block.javadoc.java",\n' + 
'\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#5C6370"\n' + 
'                }\n' + 
'            },\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    //Changes new keyword in C#\n' + 
'                    "keyword.operator.expression.new.cs",\n' + 
'                    //Changes !, &&, etc. in C#\n' + 
'                    "keyword.operator.logical.cs",\n' + 
'                    //Makes ++ in C# purple\n' + 
'                    "keyword.operator.increment.cs",\n' + 
'                    //Makes = in C# purple\n' + 
'                    "keyword.operator.assignment.cs",\n' + 
'                    // Makes + in C# purple\n' + 
'                    "keyword.operator.arithmetic.cs",\n' + 
'                    //Makes += in C# purple\n' + 
'                    "keyword.operator.assignment.compound.cs",\n' + 
'                    //Makes == in C# purple\n' + 
'                    "keyword.operator.comparison.cs",\n' + 
'                    //Makes => in C# purple\n' + 
'                    "keyword.operator.arrow.cs",\n' + 
'                    //Makes ?? in C# purple\n' + 
'                    "keyword.operator.null-coalescing.cs",\n' + 
'                    //Makes ternary ? in C# purple\n' + 
'                    "keyword.operator.conditional.question-mark.cs",\n' + 
'                    //Makes ternary : in C# purple\n' + 
'                    "keyword.operator.conditional.colon.cs",\n' + 
'                    //Makes > in C# purple\n' + 
'                    "keyword.operator.relational.cs"\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#C678DD" // purple\n' + 
'                }\n' + 
'            }\n' + 
'\n' + 
'        ],\n' + 
'    }, //End of Atom One Dark\n' + 
'\n' + 
'    "[Eclipse Dark]": {\n' + 
'        "textMateRules": [\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes the colors of the periods in the import statements */\n' + 
'                    "punctuation.separator.java"\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#DAE8F7"\n' + 
'                }\n' + 
'            },\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes the package name color to blue.\n' + 
'                    Note that the import names cannot change color */\n' + 
'                    "storage.modifier.package.java"\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#4A99C3"\n' + 
'                }\n' + 
'            },\n' + 
'\n' + 
'\n' + 
'            {\n' + 
'                "scope": [\n' + 
'                    /** Changes the top and bottom of comments */\n' + 
'                    "punctuation.definition.comment.java",\n' + 
'                    /** Changes the color of the * character in body comments.\n' + 
'                    Also changes the tag descriptions in comments */\n' + 
'                    "comment.block.javadoc.java",\n' + 
'                    /** Changes @ tags to gray */\n' + 
'                    "punctuation.definition.annotation.java"\n' + 
'\n' + 
'\n' + 
'                ],\n' + 
'                "settings": {\n' + 
'                    "foreground": "#939393"\n' + 
'                }\n' + 
'            }\n' + 
'        ],\n' + 
'\n' + 
'    },\n' + 
'},\n' + 
'\n' + 
'"[python]": {\n' + 
'},\n' + 
'"json.schemas": [\n' + 
'],\n' + 
'"editor.codeActionsOnSave": {\n' + 
'},\n' + 
'\n' + 
'//Helps work with JSON while using Java\n' + 
'"java.project.referencedLibraries": [\n' + 
'    "lib/**/*.jar",\n' + 
'    "json-20230618.jar"\n' + 
'],\n' + 
'\n' + 
'"liveServer.settings.donotShowInfoMsg": true,\n' + 
'\n' + 
'"workbench.editorAssociations": {\n' + 
'    "*.db": "sqlite-viewer.option"\n' + 
'},\n' + 
'\n' + 
'"workbench.colorTheme": "Atom One Dark",\n' + 
'\n' + 
'"files.associations": {\n' + 
'    "*.css": "tailwindcss"\n' + 
'},\n' + 
'\n' + 
'"yaml.schemas": {\n' + 
'    "Kubernetes": "*.yaml"\n' + 
'},\n' + 
'"git.autofetch": true,\n' + 
'"cSpell.userWords": [\n' + 
'    "autofetch",\n' + 
'    "axios",\n' + 
'    "donot",\n' + 
'    "emailjs",\n' + 
'    "Intellij",\n' + 
'    "javadoc",\n' + 
'    "jsonify",\n' + 
'    "pyenv",\n' + 
'    "pyfile",\n' + 
'    "tailwindcss",\n' + 
'    "typeparameters",\n' + 
'    "vite"\n' + 
'],\n' + 
'"diffEditor.ignoreTrimWhitespace": false,\n' + 
'"explorer.fileNesting.patterns": {\n' + 
'    "*.ts": "${capture}.js",\n' + 
'    "*.js": "${capture}.js.map, ${capture}.min.js, ${capture}.d.ts",\n' + 
'    "*.jsx": "${capture}.js",\n' + 
'    "*.tsx": "${capture}.ts",\n' + 
'    "tsconfig.json": "tsconfig.*.json",\n' + 
'    "package.json": "package-lock.json, yarn.lock, pnpm-lock.yaml, bun.lockb",\n' + 
'    "*.sqlite": "${capture}.${extname}-*",\n' + 
'    "*.db": "${capture}.${extname}-*",\n' + 
'    "*.sqlite3": "${capture}.${extname}-*",\n' + 
'    "*.db3": "${capture}.${extname}-*",\n' + 
'    "*.sdb": "${capture}.${extname}-*",\n' + 
'    "*.s3db": "${capture}.${extname}-*"\n' + 
'}\n' + 
'\n' + 
'}\n' +
''

</script>