from termcolor import colored as c

"""
Creates the src/data/settings.vue file from the 
real_settings.txt file. 

The real_settings.txt file should contain the json data
from the settings.json file in VS Code.
"""

the_str = ""

with open("real_settings.txt", "r") as file:
    for line in file:
        the_str += f"'{line.rstrip()}\\n' + \n"

the_str = the_str[:-7] + "\\n' +\n''"
the_str = the_str.replace("that's above", "that\\'s above")
the_str = the_str.replace("doesn't work", "doesn\\'t work")

the_str = (
    "<script>\n\n"
    "//This string contains the VSCode Settings. Generated by the create_settings_file python file.\n\n"
    "export const settings =\n\n"
    f"{the_str}"
    "\n\n</script>"
)

path_to_settings_vue = "../src/data/CompSci/settings.vue"

with open(path_to_settings_vue, "w") as file:
    file.write(the_str)
    
print(c("Go click the copy button and paste the json data in \"results.txt\"", "blue"))